hery_music_store_inventory/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import show_main, create_item, show_xml, show_json, show_xml_by_id, show_json_by_id, register, login_user, logout_user, increase_item, decrease_item ,delete, get_item_json, add_item_ajax, delete_ajax, create_item_flutter




app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-item', create_item, name='create_item'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'), 
    path('xml/<int:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'), 
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('increase/<int:id>', increase_item, name='increase'),
    path('decrease/<int:id>', decrease_item, name='decrease'),
    path('delete/<int:id>', delete, name='delete'),
    path('get-item/', get_item_json, name='get_item_json'),
    path('create-ajax/', add_item_ajax, name='add_item_ajax'),
    path('delete-ajax/<int:id>', delete_ajax, name = 'delete_ajax'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Item(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    price = models.IntegerField()
    description = models.TextField()
    amount = models.IntegerField()

main/forms.py
from django.forms import ModelForm
from main.models import Item

class ItemForm(ModelForm):
    class Meta:
        model = Item
        fields = ["name", "price", "description", "amount"]

main/views.py
import datetime
import json
from django.shortcuts import render
from django.http import HttpResponseNotFound, HttpResponseRedirect, JsonResponse
from main.forms import ItemForm
from django.urls import reverse
from main.models import Item
from django.http import HttpResponse
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    items = Item.objects.filter(user = request.user)

    counter  = 0
    for item in items: #for loop untuk menghitung total item di aplikasi
        counter += item.amount

    context = {
        'application_name': 'Hery Music Store Inventory',
        'user_name': request.user.username,
        'my_name': 'Mahoga Aribowo Heryasa',
        'class': 'PBP D',
        'items': items,
        'counter': counter,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_item(request):
    form = ItemForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        item = form.save(commit=False)
        item.user = request.user
        item.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {'form': form}
    return render(request, "create_item.html", context)

def show_xml(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = Item.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Item.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main")) 
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

def increase_item(request, id):
    # item_index = int(request.POST.get('item_index'))
    # data = Item.objects.filter(user = request.user)
    # item = data[item_index]
    item = Item.objects.get(pk=id)
    item.amount += 1
    item.save()

    return redirect('main:show_main')

def decrease_item(request, id):
    # item_index = int(request.POST.get('item_index'))
    # data = Item.objects.filter(user = request.user)
    # item = data[item_index]
    item = Item.objects.get(pk=id)
    item.amount -= 1
    item.save()

    if item.amount <= 0:
        item.delete()

    return redirect('main:show_main')

def delete(request, id):
    # item_index = int(request.POST.get('item_index'))
    # data = Item.objects.filter(user = request.user)
    # item = data[item_index]
    item = Item.objects.get(pk=id)
    item.delete()

    return redirect('main:show_main')

def get_item_json(request):
    item = Item.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', item))

@csrf_exempt
def add_item_ajax(request):
    if request.method == 'POST':
        name = request.POST.get("name")
        description = request.POST.get("description")
        price = request.POST.get("price")
        amount = request.POST.get("amount")
        user = request.user

        new_item = Item(name=name, description=description, price=price, amount=amount, user=user)
        new_item.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def delete_ajax(request, id):
    item = Item.objects.get(pk=id)
    item.delete()

    return HttpResponse(b"DELETED", status=201)

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':
        
        data = json.loads(request.body)

        new_product = Item.objects.create(
            user = request.user,
            name = data["name"],
            price = int(data["price"]),
            description = data["description"],
            amount = int(data["amount"]),
        )

        new_product.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create_item.html
{% extends 'base.html' %} 
<style>
    .intro {
        height: 100%;
    }

    .bg-image-vertical {
        position: relative;
        background-repeat: repeat;
        background-position: right center;
        background-size: auto 100%;
    }
</style>

{% block content %}
<section class="intro">
    <div class="bg-image-vertical h-100" style="background-color: #f2f2f2;
            background-image: url(https://guitar.com/wp-content/uploads/2021/04/guitar-shop@1400x1050.jpg);
          ">
      <div class="mask d-flex align-items-center">
        <div class="container" style="margin-top: 6rem; margin-bottom: 6rem;">
          <div class="row justify-content-center">
            <div class="col-12 col-lg-10">
              <div class="card" style="border-radius: 1rem;">
                <div class="card-body p-5" >
  
                  <h1 class="mb-5 text-center">Item Atribute</h1>
                  <br/>
                  <form method="POST">
                    {% csrf_token %}
                    <div class="form-outline mb-4">
                        <input type="text" id="form6Example3" class="form-control" placeholder="Name" name="name"/>
                    </div>
                    <div class="form-outline mb-4">
                      <input type="number" id="form6Example4" class="form-control" placeholder="Price" name="price"/>
                    </div>
                    <div class="form-outline mb-4">
                      <input type="number" id="form6Example5" class="form-control" placeholder="Amount" name="amount"/>
                    </div>
                    <div class="form-outline mb-4">
                      <textarea class="form-control" id="form6Example7" rows="4" placeholder="Description" name="description"></textarea>
                    </div>

                    <button type="submit" class="btn btn-dark btn-rounded btn-block" value="Add Product">Place Item in Inventory</button>
                  </form>
  
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
    <title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <section class="vh-100" style="background-color: #5a0000;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col col-xl-10">
              <div class="card" style="border-radius: 1rem;">
                <div class="row g-0">
                  <div class="col-md-6 col-lg-5 d-none d-md-block">
                    <img src="https://i.pinimg.com/564x/65/fb/e8/65fbe8ca3f041e799c434c15509e71e2.jpg"
                      alt="login form" class="img-fluid" style="border-radius: 1rem 0 0 1rem;" />
                  </div>
                  <div class="col-md-6 col-lg-7 d-flex align-items-center">
                    <div class="card-body p-4 p-lg-5 text-black">
      
                      <form method="POST" action="">
                        {% csrf_token %}
                        <div class="d-flex align-items-center mb-3 pb-1">
                          <img src="https://clipartcraft.com/images/guitar-logo-8.png" alt="Logo" width="50" height="50" style="margin-right: 10px;">
                          <span class="h2 fw-bold mb-0">Hery Music Store Inventory</span>
                        </div>
                        <br/> <br/> 
                        <h5 class="fw-normal mb-3 pb-3" style="letter-spacing: 1px;">Login</h5>
      
                        <div class="form-outline mb-4">
                          <input type="text" name="username" id="Username" class="form-control form-control-lg" placeholder="Username"/>
                          <!-- <label for="Username">Username</label> -->
                        </div>
      
                        <div class="form-outline mb-4">
                          <input type="password" name="password" id="pwpw" class="form-control form-control-lg" placeholder="Password"/>
                          <!-- <label class="form-label" for="pwpw">Password</label> -->
                        </div>
      
                        <div class="pt-1 mb-4">
                          <button class="btn btn-dark btn-lg btn-block" type="submit" value="Login">Login</button>
                        </div>
                        
                        {% if messages %}
                        <ul>
                            {% for message in messages %}
                                <li>{{ message }}</li>
                            {% endfor %}
                        </ul>
                        {% endif %}   
      
                        <p class="mb-5 pb-lg-2" style="color: #393f81;">Don't have an account? <a href="{% url 'main:register' %}"
                            style="color: #393f81;">Register here</a></p>
                      </form>
      
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
      
</div>

{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}

{% block meta %}
    <style>
        .card {
        width: 500px; /* Adjust the desired width */
        height: 600px; /* Adjust the desired height */
        }

        .card-title {
            height: 40px;
            white-space: nowrap;
        }

        .card-body {
            background-color: #920000;
        }

        .card-text {
            color: #ecbdbd;
        }

        .navbar {
            background-color: #920000;
        }

        footer {
            height: 100px;
            bottom: 0;
            width: 100%;
            position:sticky;
            text-align: center;
            background-color: #5a0000;

        }

        /* below this is for table */
        th, td{
            padding: 8px;
            text-align:left;
        }

        table {
            border-collapse: collapse;
            width: 100%;
            border: 1px solid #000000;
        } 

        th {
            background-color: #5a0000;
            color: #f2f2f2;
        }
        
        tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        tr:nth-child(odd) {
            background-color: #920000;
            color: #f2f2f2;
        }

        tr:last-of-type {
            background-color:#5a0000;
            color: #f2f2f2;
        }

        .text-with-stroke{
            -webkit-text-stroke: 1.5px black;
        }

    </style>
{% endblock meta %}

{% block content %}
    <nav class="navbar navbar-dark shadow fixed-top">
        <div class="container-fluid">
        <a class="navbar-brand" style="color: #f2f2f2;">
            <img src="https://clipartcraft.com/images/guitar-logo-8.png" alt="logo" width="50" height="50">   Hery Music Store Inventory
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: #f2f2f2;">
                    Option
                </a>
                <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'main:logout' %}">Logout</a></li>
                <li><a class="dropdown-item" href="{% url 'main:create_item' %}">Add Item</a></li>
                <li><button class="dropdown-item" data-bs-toggle="modal" data-bs-target="#addItem">Add Item by AJAX</button></li>
                </ul>
            <li class="nav-item dropdown">
                    <a class="nav-link" href="#">last login: {{last_login}}.</a>
            </li>
            </li>
            </ul>
        </div>
        </div>
    </nav>

    <div style="background: url(https://guitar.com/wp-content/uploads/2021/04/guitar-shop@1400x1050.jpg); font-family:Impact, Haettenschweiler, 'Arial Narrow Bold', sans-serif" class="jumbotron bg-cover text-white">
        <div class="container py-5 text-center">
            <br/> <br/> <br/><br/><br/><br/>
            <h1 class="display-4 font-weight-bold text-with-stroke">Welcome {{user_name}}, to Your Inventory</h1>
            <br/>
            <br/> <br/> <br/> <br/>
            <a href= "{% url 'main:create_item' %}" class="btn btn-light">Add Item</a>
            <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#addItem">Add Item by AJAX</button>
        </div>
    </div>
  
    <section class="py-5">
        <br/>
        <div class="container">
            <!-- <h1 style="color:#5a0000; text-align: center;">Total Items Stored in Inventory: {{counter}}</h1> -->
            <h1 style="color:#5a0000; text-align: center;" id="item_total"></h1>
            <br/> <br/>
            <h5 style="color:#5a0000;"> List Item </h5>
            <table id="item_list"></table>
            <br/> <br/> <br/>
            <h5 style="color:#5a0000;"> Catalog </h5>
            <div class="row" id="item_card"></div>
        </div>
    </section>

    </br>

    <footer id="sticky-footer" class="flex-shrink-0 py-4">
        <div class="container text-center">
          <small style="color: #f2f2f2;">Copyright &copy; {{ my_name }} of Class: {{ class }}</small>
        </div>
    </footer>

    <div class="modal fade" id="addItem" tabindex="-1" aria-labelledby="addItemLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Item Atribute</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form id="form" onsubmit="return false;">
                        {% csrf_token %}
                        <div class="mb-3">
                            <!-- <label for="name" class="col-form-label">Name:</label> -->
                            <input type="text" class="form-control" id="name" name="name" placeholder="Name"></input>
                        </div>
                        <div class="mb-3">
                            <!-- <label for="description" class="col-form-label">Description:</label> -->
                            <textarea class="form-control" id="description" name="description" placeholder="Description"></textarea>
                        </div>
                        <div class="mb-3">
                            <!-- <label for="price" class="col-form-label">Price:</label> -->
                            <input type="number" class="form-control" id="price" name="price" placeholder="Price"></input>
                        </div>
                        <div class="mb-3">
                            <!-- <label for="amount" class="col-form-label">Amount:</label> -->
                            <input type="number" class="form-control" id="amount" name="amount" placeholder="Amount"></input>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Item</button>
                </div>
            </div>
        </div>
    </div>
    
    <script>
        async function getItem() {
            return fetch("{% url 'main:get_item_json' %}").then((res) => res.json())
        }

        async function refreshItem() {
            const items = await getItem()
            document.getElementById("item_list").innerHTML = ""
            let htmlStringTable = `<tr>
                <th style="border: 1px solid #000000;">No</th>
                <th style="border: 1px solid #000000;">Item</th>
            </tr>`
            let loopCount = 1
            items.forEach((item) => {
                htmlStringTable += `\n<tr>
                <td style="border: 1px solid #000000;">${loopCount}</td>
                <td style="border: 1px solid #000000;">${item.fields.name}</td>
            </tr>` 
                loopCount++
            })
            document.getElementById("item_list").innerHTML = htmlStringTable

            document.getElementById("item_card").innerHTML = ""
            let htmlStringCard = ``
            let itemCount = 0
            items.forEach((item) => {
                htmlStringCard += 
                `<div class="col-md-3 mb-5">
                    <div class="card" style="width: 18rem;">
                        <img class="card-img-top" src="https://clipartcraft.com/images/guitar-logo-8.png" alt="item">
                        <div class="card-body">
                            <h5 class="card-title" style="color:#f2f2f2; white-space: wrap; ">${item.fields.name}</h5>
                            <p></p>
                            <p class="card-text">Description: ${item.fields.description}</p>
                            <p class="card-text">Price: ${item.fields.price}</p>
                            <p class="card-text">Amount: ${item.fields.amount}</p>
                            <a href="increase/${item.pk}" class="btn btn-light">+</a>
                            <a href="decrease/${item.pk}" class="btn btn-light">-</a>
                            <a href="delete/${item.pk}" class="btn btn-light">DEL</a>
                            <button type="button" class="btn btn-light" onclick="deleteAJAX(${item.pk})">DEL AJAX</button>
                        </div>
                        <div class="card-footer" style="background-color: #ffffff;">
                            <small class="text-muted">Date Added: ${item.fields.date_added}</small>
                        </div>
                    </div>
                </div>` 
                itemCount += item.fields.amount
            })
            document.getElementById("item_card").innerHTML = htmlStringCard

            document.getElementById("item_total").innerHTML = `Total Items Stored in Inventory: ` + itemCount
        }

        refreshItem()

        function addItem() {
            fetch("{% url 'main:add_item_ajax' %}", {
                method: "POST",
                body: new FormData(document.querySelector('#form'))
            }).then(refreshItem)

            document.getElementById("form").reset()
            return false
        }

        document.getElementById("button_add").onclick = addItem

        function deleteAJAX(itemId) {
            fetch("/delete-ajax/" + itemId, {
                method: "POST",
            }).then(refreshItem)

            document.getElementById("form").reset()
            return false
        }
    </script>
{% endblock content %} 

main/templates/register.html
{% extends 'base.html' %}

{% block meta %}
    <title>Register</title>
{% endblock meta %}

{% block content %}  

<div class = "login">
    
    <section class="vh-100" style="background-color: #5a0000;">
        <div class="container py-5 h-100">
          <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-12 col-md-8 col-lg-6 col-xl-5">
              <div class="card shadow-2-strong" style="border-radius: 1rem;">
                <div class="card-body p-5 text-left">
      
                  <h3 class="mb-5">Sign in</h3>
                  
                  <form method="POST">
                    {% csrf_token %} 
                    <div class="form-outline mb-4">
                      <input type="text" id="id_username"  class="form-control form-control-lg" name="{{ form.username.name }}" placeholder="Username"/>
                    </div>
        
                    <div class="form-outline mb-4">
                      <input type="password" id="id_password1" class="form-control form-control-lg" name="{{ form.password1.name }}" placeholder="Password"/>
                    </div>
        
                    <div class="form-outline mb-4">
                      <input type="password" id="id_password2" class="form-control form-control-lg" name="{{ form.password2.name }}" placeholder="Re-type Password"/>
                    </div>
                    <hr class="my-4">
                    <button class="btn btn-primary btn-dark btn-block" type="submit" name="submit" value="Daftar">Register</button>
                  </form>
                  {% if messages %}  
                  <ul>   
                      {% for message in messages %}  
                          <li>{{ message }}</li>  
                          {% endfor %}  
                  </ul>   
                  {% endif %} 
                </div>
              </div>
            </div>
          </div>
        </div>
    </section>  
</div>  

{% endblock content %}